# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16e797102e2f46fabb253ee9dda12c1c"
name = "power"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_app_proxy,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
prefix = "apps"
subpath = "shop-dash"
url = "https://example.com/api/app-proxy"
